name: app_review
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:                                                            
  sdk: '>=2.10.0 <3.0.0'   

dependencies:
  http: ^0.12.0+4
  package_info: ^0.4.0+13
  url_launcher: '>=5.4.10 <6.0.3'
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.appleeducate.appreview
    pluginClass: AppReviewPlugin
 